### ISSUE TITLE
Templates are not found when packaging is set to jar

### ISSUE THREAD

**Issue by igaidai4uk** [mjeanroy/springmvc-mustache#1]
If packaging is set to _jar_ none of templates are found. According to [documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content), _webapp_ folder is excluded from _jar_.

**Comment by mjeanroy** [comment]
Hi,

Thank you very much for your feedback.

Internally, this library use the spring resource loader bean registered in your application context. I don't know about your configuration but what you probably get is an instance of AnnotationConfigWebApplicationContext and by default it will look for resources under the root of your web application (i.e `src/main/webapp`).

When your templates are located under the resource directory, it fails to find templates because this resource loader search on the classpath if resource path is prefixed with `classpath:`. The best solution for now is probably to use this prefix by default:
- Create a file named `mustache.properties` at the root of your classpath.
- Define a property `mustache.prefix` and set it to `classpath:/templates/`.

I'm not sure that this library should try to prepend this prefix automatically, but I will try to find a better solution for this use case.

**Comment by igaidai4uk** [comment]
> classpath:/templates/
works great, thanks!
